config/routes.rb
CursoRuby::Application.routes.draw do

  root to: 'sitio#inicio'

  
  get 'sitio/acerca' => 'sitio#acerca'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sitio_controller.rb
class SitioController < ApplicationController
  def inicio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sitio_helper.rb
module SitioHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CursoRuby</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%=render template: "layouts/header"%>


<%= yield %>

<%=render template:"sitio/footer"%>

</body>
</html>

app/views/layouts/header.html.erb
<%= link_to "Inicio",root_path%>
<%= link_to "Acerca",sitio_acerca_path%>

app/views/sitio/acerca.html.erb
<h1>Acerca de nosotros</h1>
<p>Pagina acerca de nosotros</p>

<%=link_to "Enlace a Oja.la" ,"http://oja.la"%> 

app/views/sitio/footer.html.erb
<div class "footer">

	<small> Creado por Irving Corrssssso</small>

</div>

app/views/sitio/inicio.html.erb
<h1>Curso Ruby On Rails</h1>
<p>Ejemplo de aplicacion utilizando Ruby On Rails
 	<%=link_to "Enlace a Oja.la" ,"http://oja.la"%>  
<button class="btn btn-large btn-primary" type="button">Large button</button>

</p>